identity = "{{.node_name}}"
chain = "mainnet"
datadir = "{{.data_folder_path}}"
nodekey = "{{.config_folder_path}}/nodekey"
staticpeers = "{{.static_nodes}}"
verbosity = "{{.log_level}}"
snapshots = false


[bor]
    heimdall = "{{.cl_node_url}}"
    milestone = true
    waypoints = false

{{if .is_validator}}
allow-insecure-unlock = true
[mine]
    gaslimit = 30000000
    gasprice = "25000000000"
    etherbase = "{{.address}}"
    extradata = "{{.node_name}}"
{{end}}

[http]
    enabled = true
    addr = "0.0.0.0"
    port = {{.rpc_port_number}}
    api = ["eth", "net", "web3", "txpool", "bor"]
    vhosts = ["*"]
    corsdomain = ["*"]

[ws]
    enabled = true
    port = {{.ws_port_number}}

[metrics]
    addr = "0.0.0.0"
    port = {{.metrics_port_number}}
