# Node parameters.
identity = "{{.node_name}}"
chain = "mainnet"
datadir = "{{.data_folder_path}}"
staticpeers = "{{.static_nodes}}"
verbosity = "{{.log_level}}"
snapshots = false

# Bor parameters.
"bor.heimdall" = "{{.cl_node_url}}"
"bor.milestone" = true
"bor.waypoints" = false

{{if .is_validator}}
# Miner parameters.
nodekey = "{{.config_folder_path}}/nodekey"
allow-insecure-unlock = true
"miner.gaslimit" = 30000000
"miner.etherbase" = "{{.address}}"
"miner.extradata" = "{{.node_name}}"
{{end}}

# HTTP RPC
"http" = true
"http.addr" = "0.0.0.0"
"http.port" = {{.rpc_port_number}}
"http.api" = ["eth", "net", "web3", "txpool", "bor"]
"http.vhosts" = ["*"]
"http.corsdomain" = ["*"]

# WS RPC
"ws" = true
"ws.port" = {{.ws_port_number}}

# Metrics
"metrics.addr" = "0.0.0.0"
"metrics.port" = {{.metrics_port_number}}
