polygon_pos_package:
  participants:
    # validators
    - kind: validator
      cl_type: heimdall-v2
      el_type: bor
      count: 10
    - kind: rpc
      cl_type: heimdall-v2
      el_type: bor
      count: 5
