polygon_pos_package:
  participants:
    - kind: validator
      cl_type: heimdall
      el_type: erigon
    - kind: rpc
      cl_type: heimdall
      el_type: erigon

  network_params:
    cl_environment: local
