polygon_pos_package:
  participants:
    # Validator nodes
    - kind: validator
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:9e65c78
      el_type: bor
      el_image: local/bor:d976a51
      count: 2
      el_bor_produce_witness: true

    # RPC nodes
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:9e65c78
      el_type: bor
      el_image: local/bor:d976a51
      el_bor_produce_witness: true
      el_bor_sync_with_witness: false
      count: 2

    - kind: rpc
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:9e65c78
      el_type: bor
      el_image: local/bor:d976a51
      el_bor_produce_witness: true
      el_bor_sync_with_witness: true
      count: 1

    - kind: rpc
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:9e65c78
      el_type: bor
      el_image: local/bor:d976a51
      el_bor_produce_witness: false
      el_bor_sync_with_witness: false
      count: 1

  additional_services:
    - prometheus_grafana
    - test_runner
