# Node parameters.
identity = "{{.node_name}}"
networkid = "{{.el_chain_id}}"
datadir = "{{.data_folder_path}}"
staticpeers = "{{.static_nodes}}"
verbosity = "{{.log_level}}"
snapshots = false
nat = "none"

# Bor parameters.
"bor.heimdall" = "{{.cl_node_url}}"
"bor.milestone" = true
"bor.waypoints" = false

# HTTP RPC
"http" = true
"http.addr" = "0.0.0.0"
"http.port" = {{.rpc_port_number}}
"http.api" = ["eth", "net", "web3", "txpool", "bor"]
"http.vhosts" = ["*"]
"http.corsdomain" = ["*"]

# WS RPC
"ws" = true
"ws.port" = {{.ws_port_number}}

# Metrics
"metrics.addr" = "0.0.0.0"
"metrics.port" = {{.metrics_port_number}}
