identity = "{{.node_name}}"
networkid = "{{.el_chain_id}}"
datadir = "{{.data_folder_path}}"
verbosity = "{{.log_level}}"

no-downloader = true
nat = "none"

# P2P
maxpeers = 200
port = {{.discovery_port_number}}
nodiscover = true
staticpeers = "{{.static_nodes}}"

[bor]
    heimdall = "{{.cl_node_url}}"
    milestone = true
    waypoints = false

{{if .is_validator}}
mine = {{.is_validator}}
{{end}}

[miner]
    gaslimit = 30000000
    gasprice = "25000000000"
    etherbase = "{{.address}}"
    extradata = "{{.node_name}}"
    sigfile = "{{.config_folder_path}}/nodekey"

# Accounts
allow-insecure-unlock = true

# JSON-RPC
ipcpath = "{{.data_folder_path}}/erigon.ipc"
[http]
    addr = "0.0.0.0"
    port = {{.rpc_port_number}}
    api = ["eth", "net", "web3", "txpool", "bor"]
    vhosts = ["*"]
    corsdomain = ["*"]
[ws]
    addr = "0.0.0.0"
    port = {{.ws_port_number}}
    api = ["eth", "net", "web3", "txpool", "bor"]
    origins = ["*"]

[metrics]
    addr = "0.0.0.0"
    port = {{.metrics_port_number}}
