# Ethereum package (L1) configuration.
ethereum_package:
  participants:
    - el_type: geth
      el_image: ethereum/client-go:v1.15.11
      cl_type: lighthouse
      cl_image: ethpandaops/lighthouse:unstable-6135f41
      use_separate_vc: true
      vc_type: lighthouse
      vc_image: ethpandaops/lighthouse:unstable-6135f41
  network_params:
    preset: minimal
    seconds_per_slot: 1

# Polygon PoS package (L2) configuration.
polygon_pos_package:
  participants:
    - kind: validator
      el_type: bor
      el_image: 0xpolygon/bor:2.2.5
      el_log_level: info
      cl_type: heimdall
      cl_image: 0xpolygon/heimdall:1.6.0
      cl_db_image: rabbitmq:4.1.2
      cl_log_level: info
      count: 2
    - kind: rpc
      el_type: bor
      cl_type: heimdall
  setup_images:
    contract_deployer: leovct/pos-contract-deployer-node-20:ed58f8a
    el_genesis_builder: leovct/pos-el-genesis-builder:96a19dd
    validator_config_generator: leovct/pos-validator-config-generator:1.6.0-0.2.4
  network_params:
    admin_private_key: "0xd40311b5a5ca5eaeb48dfba5403bde4993ece8eccf4190e98e19fcd4754260ea"
    ## Validators parameters.
    preregistered_validator_keys_mnemonic: sibling lend brave explain wait orbit mom alcohol disorder message grace sun
    validator_stake_amount_eth: 10000
    validator_top_up_fee_amount_eth: 2000
    ## Consensus Layer parameters
    cl_chain_id: heimdall-4927
    cl_environment: mainnet
    cl_span_poll_interval: 0m15s
    cl_checkpoint_poll_interval: 1m0s
    ## Execution Layer parameters.
    el_chain_id: "4927"
    el_block_interval_seconds: 2
    el_sprint_duration: 16
    el_span_duration: 128
    el_gas_limit: 10_000_000
  additional_services:
    # - blockscout
    - prometheus_grafana
    - test_runner
    # - tx_spammer
