identity = "{{.node_name}}"
chain = "{{.config_folder_path}}/genesis.json"
verbosity = 3
datadir = "{{.data_folder_path}}"
syncmode = "full"

[p2p]
    maxpeers = 200
    bind = "0.0.0.0"
    port = {{.discovery_port_number}}
    nodiscover = true
    [p2p.discovery]
        static-nodes = {{.static_nodes}}

[heimdall]
    url = "{{.cl_node_url}}"

[miner]
    mine = {{.is_validator}}
    gaslimit = 30000000
    gasprice = "25000000000"
    etherbase = "{{.address}}"
    extradata = "{{.node_name}}"

{{if .is_validator}}
[accounts]
    allow-insecure-unlock = true
    password = "{{.config_folder_path}}/password.txt"
    unlock = ["{{.address}}"]
{{end}}

[jsonrpc]
    ipcpath = "{{.data_folder_path}}/bor.ipc"
    [jsonrpc.http]
        enabled = true
        host = "0.0.0.0"
        port = {{.rpc_port_number}}
        api = ["eth", "net", "web3", "txpool", "bor"]
        vhosts = ["*"]
        corsdomain = ["*"]
    [jsonrpc.ws]
        enabled = true
        host = "0.0.0.0"
        port = {{.ws_port_number}}
        api = ["eth", "net", "web3", "txpool", "bor"]
        origins = ["*"]

[telemetry]
    metrics = true

