verbosity = {{.log_level_to_int}}
{{if eq .kind "stateless"}}

{{else}}

{{end}}

{{if .el_produce_witness}}

{{end}}

{{if .el_sync_with_witness}}

{{end}}

identity = "{{.node_name}}"
chain = "{{.config_folder_path}}/genesis.json"
datadir = "{{.data_folder_path}}"
syncmode = "stateless"
syncmode = "full"
witnessprotocol = true
syncwithwitnesses = true
[p2p]
port = {{.discovery_port_number}}
maxpeers = 200
bind = "0.0.0.0"
nodiscover = true
nodekey = "{{.data_folder_path}}/nodekey"
[p2p.discovery]
static-nodes = {{.static_nodes}}

[heimdall]
url = "{{.cl_api_url}}"
ws-address = "{{.cl_node_ws_url}}"

[accounts]


{{if eq .kind "validator"}}
allow-insecure-unlock = true
password = "{{.config_folder_path}}/password.txt"
unlock = ["{{.address}}"]
[miner]

{{end}}

mine = true
gaslimit = 45000000
gasprice = "25000000000"
etherbase = "{{.address}}"
extradata = "{{.node_name}}"
[jsonrpc]
ipcpath = "{{.data_folder_path}}/bor.ipc"
[jsonrpc.http]
port = {{.rpc_port_number}}
enabled = true
host = "0.0.0.0"
api = ["admin", "eth", "net", "web3", "txpool", "bor"]
vhosts = ["*"]
corsdomain = ["*"]
[jsonrpc.ws]
port = {{.ws_port_number}}
enabled = true
host = "0.0.0.0"
api = ["admin", "eth", "net", "web3", "txpool", "bor"]
origins = ["*"]

[telemetry]
metrics = true
prometheus-addr = "0.0.0.0:{{.metrics_port_number}}"
