name: kurtosis-lint

on:
  pull_request:
    paths-ignore:
      - docs/**
      - .github/workflows/docs-*.yaml

  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - .github/workflows/docs-*.yaml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Pre kurtosis run
        uses: ./.github/actions/kurtosis-pre-run
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}

      - name: Run kurtosis linter
        run: kurtosis lint .
